name: Build macOS Plugin

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          brew update
          brew install cmake ninja glib wireshark
          brew link --overwrite wireshark

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..

      - name: Build Plugin
        run: |
          cmake --build build --config Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: macos-plugin
          path: build/*.so
